spring.application.name=payx-wallet

# Server port (optional; default is 8080)
server.port=8083

# MongoDB config
spring.data.mongodb.uri=mongodb://localhost:27017/payx_wallet_db

# Logging a bit more detail for debugging
logging.level.org.springframework.web=INFO
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
